baseurl = "https://yarelm.github.io/"
title = "Yarel Maman's Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Yarel Maman's Blog"
    description = "Piecing the Puzzle"
    github = "https://github.com/yarelm"
    twitter = "https://twitter.com/YarelMam"
    email = "yarel.maman@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
